spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=Europe/Moscow&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: off
    locations: classpath:db/migration

blog:
  title: GalvanoBlog
  subtitle: Записки гальванотехника
  phone: +7 999 777-77-77
  email: solshevskiy@gmail.com
  copyright: Сергей Ольшевский
  copyrightFrom: 2021
  announceLength: 150